#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker324"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "01768ed3047344ce910b1c4c560e5972" }
]

[assets]
directory = "./public"
